syntacore/snippy

llvm/tools/llvm-snippy/README.md

@asi-sc please take a look at my suggested changes. 
I mostly didn't add too much, rather some minor clarifications here and there. I also restructured the doc a bit. Anyways, let me know what to change :)

Proofreading main readme 

---

llvm/test/tools/llvm-snippy/redefine-sp-ext-funcs-warn.yaml
llvm/tools/llvm-snippy/llvm-snippy.cpp

Forbid stack pointer redefinition when using externl funcs

[snippy] forbid sp redefinition when using external funcs

---

llvm/test/tools/llvm-snippy/rvv-config-histogram/Inputs/rvv-unit-sew64-lmul2.yaml
llvm/test/tools/llvm-snippy/rvv-config-histogram/Inputs/rvv-unit-sew64-lmulf2.yaml
llvm/test/tools/llvm-snippy/rvv-zvbb.yaml
llvm/test/tools/llvm-snippy/rvv-zvbc-lmul2.yaml
llvm/test/tools/llvm-snippy/rvv-zvbc-lmulf2.yaml
llvm/test/tools/llvm-snippy/rvv-zvbc-sew32.yaml
llvm/test/tools/llvm-snippy/rvv-zvbc.yaml
llvm/tools/llvm-snippy/lib/Simulator/RISCVSimulator.cpp
llvm/tools/llvm-snippy/lib/Target/RISCV/RISCVGenerated.h
llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp

[snippy] Add support for Zvbk, Zvbb and Zvbc extensions.

[snippy] Add support for Zvbk, Zvbb and Zvbc extensions.

---

llvm/test/tools/llvm-snippy/branches/branches-reserved-regs.yaml
llvm/test/tools/llvm-snippy/reserved-regs/Inputs/stack-all-reserved-layout.yaml
llvm/tools/llvm-snippy/lib/LoopLatcherPass.cpp

Fix register reservation for loop latch

[snippy] Fix register reservation for loop latch

---

llvm/tools/llvm-snippy/include/snippy/Generator/GeneratorContext.h
llvm/tools/llvm-snippy/lib/Generator/GeneratorContext.cpp
llvm/tools/llvm-snippy/lib/Simulator/CMakeLists.txt

[snippy] Put the function call in a separate variable

[snippy] Put the function call in a separate variable

---

llvm/test/tools/llvm-snippy/linker-script-phdrs.yaml
llvm/tools/llvm-snippy/include/snippy/Config/MemoryScheme.h
llvm/tools/llvm-snippy/include/snippy/Generator/Linker.h
llvm/tools/llvm-snippy/lib/Config/Config.cpp
llvm/tools/llvm-snippy/lib/Generator/Linker.cpp

[snippy] Add ability to specify programm header to put section in.

[snippy] Add ability to specify programm header to put section in.

---

llvm/test/tools/llvm-snippy/branches/regs-reserv-loop.yaml
llvm/tools/llvm-snippy/include/snippy/Generator/RegReservForLoop.h
llvm/tools/llvm-snippy/include/snippy/Target/Target.h
llvm/tools/llvm-snippy/lib/LoopLatcherPass.cpp
llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp
llvm/tools/llvm-snippy/lib/Target/X86/Target.cpp

[snippy] Optimize registers reservation for loops

[snippy] Optimize registers reservation for loops

---

llvm/test/tools/llvm-snippy/gen-plan-verification-calls.yaml
llvm/test/tools/llvm-snippy/gen-plan-verification-pc-distance.yaml
llvm/test/tools/llvm-snippy/gen-plan-verification-warn.yaml
llvm/tools/llvm-snippy/include/snippy/CreatePasses.h
llvm/tools/llvm-snippy/include/snippy/Generator/GenerationLimit.h
llvm/tools/llvm-snippy/include/snippy/Support/DiagnosticInfo.h
llvm/tools/llvm-snippy/lib/BlockGenPlanWrapperPass.cpp
llvm/tools/llvm-snippy/lib/BlockGenPlanWrapperPass.h
llvm/tools/llvm-snippy/lib/BlockGenPlanningPass.cpp
llvm/tools/llvm-snippy/lib/CMakeLists.txt
llvm/tools/llvm-snippy/lib/FlowGenerator.cpp
llvm/tools/llvm-snippy/lib/Generator/GenerationLimit.cpp
llvm/tools/llvm-snippy/lib/InitializePasses.h
llvm/tools/llvm-snippy/lib/InstructionsPostProcessPass.cpp
llvm/tools/llvm-snippy/lib/PostGenVerifierPass.cpp

Determine RequestLimit type on first addition

[snippy] determine RequestLimit type on first addition

---

llvm/tools/llvm-snippy/include/snippy/Generator/Linker.h
llvm/tools/llvm-snippy/lib/Config/MemoryScheme.cpp
llvm/tools/llvm-snippy/lib/Generator/Generation.cpp
llvm/tools/llvm-snippy/lib/Simulator/RISCVSimulator.cpp
llvm/tools/llvm-snippy/llvm-snippy.cpp

[snippy] Use more specialized standard algorithms

[snippy] Use more specialized standard algorithms

---

llvm/tools/llvm-snippy/include/snippy/Config/RegisterHistogram.h
llvm/tools/llvm-snippy/include/snippy/Config/Valuegram.h
llvm/tools/llvm-snippy/include/snippy/Support/Utils.h
llvm/tools/llvm-snippy/include/snippy/Support/YAMLHistogram.h
llvm/tools/llvm-snippy/include/snippy/Support/YAMLUtils.h
llvm/tools/llvm-snippy/lib/Config/CMakeLists.txt
llvm/tools/llvm-snippy/lib/Config/RegisterHistogram.cpp
llvm/tools/llvm-snippy/lib/Config/SerDesUtils.cpp
llvm/tools/llvm-snippy/lib/Config/Valuegram.cpp
llvm/tools/llvm-snippy/lib/Support/Utils.cpp

[snippy]: Implement extended valuegram format

[snippy]: Implement extended valuegram format

---

llvm/tools/llvm-snippy/include/snippy/Support/Options.h

[snippy]: Make OptionsStorage default constructible

[snippy]: Make OptionsStorage default constructible

---

llvm/tools/llvm-snippy/lib/Config/FPUSettings.cpp

[snippy]: Use explicit ctor for Error -> Expected conversions

[snippy]: Use explicit ctor for Error -> Expected conversions

---

llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp

[snippy][NFC]: Drop dead code for LR/SC pairs

[snippy][NFC]: Drop dead code for LR/SC pairs

---

llvm/test/tools/llvm-snippy/gen-plan-verification-pc-distance.yaml
llvm/test/tools/llvm-snippy/gen-plan-verification-size-limit-bad.yaml
llvm/tools/llvm-snippy/include/snippy/Generator/GenerationLimit.h
llvm/tools/llvm-snippy/include/snippy/Generator/GenerationRequest.h
llvm/tools/llvm-snippy/include/snippy/Generator/GeneratorContext.h
llvm/tools/llvm-snippy/include/snippy/Support/Utils.h
llvm/tools/llvm-snippy/lib/BlockGenPlanningPass.cpp
llvm/tools/llvm-snippy/lib/Generator/Generation.cpp
llvm/tools/llvm-snippy/lib/Generator/GenerationLimit.cpp
llvm/tools/llvm-snippy/lib/PostGenVerifierPass.cpp

Added plan verification for size limits 
- added plan verification for size limits
- fixed size limit overflow with -num-instrs=all
- fixed typos

Added plan verification for size limits

---

llvm/test/tools/llvm-snippy/floating-point/model-heuristic-no-model-err.yaml
llvm/tools/llvm-snippy/include/snippy/Config/FPUSettings.h
llvm/tools/llvm-snippy/lib/Config/FPUSettings.cpp
llvm/tools/llvm-snippy/lib/Generator/Generation.cpp
llvm/tools/llvm-snippy/lib/Generator/GeneratorContext.cpp
llvm/tools/llvm-snippy/llvm-snippy.cpp

[snippy] create model float overwrite heuristic

[snippy] create model float overwrite heuristic

---

llvm/test/tools/llvm-snippy/dump-mir.yaml
llvm/tools/llvm-snippy/include/snippy/Config/MemoryScheme.h
llvm/tools/llvm-snippy/include/snippy/Generator/GlobalsPool.h
llvm/tools/llvm-snippy/include/snippy/Generator/LLVMState.h
llvm/tools/llvm-snippy/lib/BlockGenPlanningPass.cpp
llvm/tools/llvm-snippy/lib/ConsecutiveLoopsVerifierPass.cpp
llvm/tools/llvm-snippy/lib/Generator/InstructionGeneratorPass.cpp
llvm/tools/llvm-snippy/lib/LoopAlignmentPass.cpp
llvm/tools/llvm-snippy/lib/LoopCanonicalizationPass.cpp
llvm/tools/llvm-snippy/lib/LoopLatcherPass.cpp
llvm/tools/llvm-snippy/lib/Support/DiagnosticInfo.cpp
llvm/tools/llvm-snippy/lib/Support/Utils.cpp
llvm/tools/llvm-snippy/llvm-snippy.cpp

[snippy] Preparation to LLVM update (19.1.2)

[snippy] Sync OS snippy

---

llvm/tools/llvm-snippy/lib/Simulator/RISCVSimulator.cpp

[snippy] add standard extensions

[snippy] add standard extesions

---

llvm/test/tools/llvm-snippy/Inputs/snippy-plugin-layout-store-only.yaml
llvm/test/tools/llvm-snippy/Inputs/snippy-plugin-layout.yaml
llvm/tools/llvm-snippy/include/snippy/Generator/Interpreter.h
llvm/tools/llvm-snippy/include/snippy/Generator/SimRunner.h
llvm/tools/llvm-snippy/include/snippy/Simulator/Simulator.h
llvm/tools/llvm-snippy/include/snippy/Support/DiagnosticInfo.h
llvm/tools/llvm-snippy/lib/Generator/Interpreter.cpp
llvm/tools/llvm-snippy/lib/Generator/SimRunner.cpp
llvm/tools/llvm-snippy/lib/Generator/SimulatorContextWrapperPass.cpp
llvm/tools/llvm-snippy/lib/Simulator/RISCVSimulator.cpp
llvm/tools/llvm-snippy/lib/Simulator/Simulator.cpp
llvm/tools/llvm-snippy/lib/Simulator/Transactions.cpp

[snippy] Replace hardcoded RAM/ROM to list of memory regions

[snippy] Replace hardcoded RAM/ROM in to list of memory regions

---

llvm/test/tools/llvm-snippy/dump-intervals-to-verify-only-add.yaml
llvm/tools/llvm-snippy/lib/Generator/IntervalsToVerify.cpp

[snippy] do not include last instr in intervals-to-verify

[snippy] do not include last instr in intervals-to-verify

---

llvm/tools/llvm-snippy/include/snippy/Config/Branchegram.h
llvm/tools/llvm-snippy/include/snippy/Generator/LoopLatcherPass.h
llvm/tools/llvm-snippy/include/snippy/Support/DiagnosticInfo.h
llvm/tools/llvm-snippy/include/snippy/Support/Utils.h
llvm/tools/llvm-snippy/include/snippy/Target/Target.h
llvm/tools/llvm-snippy/lib/Config/Branchegram.cpp
llvm/tools/llvm-snippy/lib/LoopLatcherPass.cpp
llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp
llvm/tools/llvm-snippy/lib/Target/X86/Target.cpp

[snippy] add loop counter branchegram section

[snippy] add loop counter branchegram section

---

llvm/tools/llvm-snippy/Model/RISCVModel/RVM.h
llvm/tools/llvm-snippy/Model/RISCVModel/RVM.hpp
llvm/tools/llvm-snippy/lib/Simulator/RISCVSimulator.cpp
llvm/tools/llvm-snippy/lib/Support/DynLibLoader.cpp

[snippy] Resolve symlinks when loading plugins via dlopen

[snippy] Resolve symlinks when loading plugins via dlopen

---

llvm/test/tools/llvm-snippy/dump-mir-check-target-triple.yaml
llvm/tools/llvm-snippy/include/snippy/Generator/SnippyModule.h
llvm/tools/llvm-snippy/lib/Generator/SnippyModule.cpp

[snippy] add target triple for generated MIR

[snippy] add target triple for generated MIR

---

llvm/tools/llvm-snippy/lib/Generator/Interpreter.cpp

[snippy] Add diagnostics for rx section overflow when tracking mode is enabled.

[snippy] Add diagnostics for rx section overflow when tracking mode is enabled.

---

llvm/test/tools/llvm-snippy/zihintpause-32.yaml
llvm/test/tools/llvm-snippy/zihintpause.yaml
llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp

[snippy] Add zihintpause support

[snippy] Add zihintpause support

---

llvm/tools/llvm-snippy/include/snippy/Config/Valuegram.h
llvm/tools/llvm-snippy/lib/Config/Valuegram.cpp

[snippy] Diagnostics for bitrange valuegram entry
As well as some typo fixes, static functions fixes.

[snippy] Diagnostics for bitrange valuegram entry

---

llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/atomic-instrs.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/basic-from-registers.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/basic.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/branches-loops.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/compressed-instrs.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/error-valuegram-operands-incompatible.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/floats-conversion-no-dest.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/floats-four-operands.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/floats-from-registers.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/floats-no-dest.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/floats-three-operands.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/floats-two-operands.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/loads-stores.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/vector-LMUL_2.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/vector-LMUL_8.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/vector-from-registers.yaml
llvm/test/tools/llvm-snippy/initialization/apply-valuegram-each-instr/vector-instrs.yaml
llvm/tools/llvm-snippy/include/snippy/Generator/GeneratorSettings.h
llvm/tools/llvm-snippy/lib/Generator/GenerationUtils.cpp
llvm/tools/llvm-snippy/llvm-snippy.cpp

[snippy] Use valuegram for output registers only under option

[snippy] Use valuegram for output registers only under option

---

llvm/tools/llvm-snippy/CMakeLists.txt
llvm/tools/llvm-snippy/lib/Support/DynLibLoader.cpp

[snippy][cmake] add install target

[snippy][cmake] add install target

---

llvm/tools/llvm-snippy/include/snippy/Config/Branchegram.h
llvm/tools/llvm-snippy/lib/Config/Branchegram.cpp
llvm/tools/llvm-snippy/lib/Generator/Generation.cpp
llvm/tools/llvm-snippy/lib/LoopCanonicalizationPass.cpp
llvm/tools/llvm-snippy/lib/LoopLatcherPass.cpp

[snippy] Add possibility to generate loops with spilled counters

[snippy] Add possibility to generate loops with spilled counters

---

llvm/tools/llvm-snippy/include/snippy/Config/Config.h
llvm/tools/llvm-snippy/include/snippy/Support/Options.h
llvm/tools/llvm-snippy/lib/Config/Config.cpp
llvm/tools/llvm-snippy/llvm-snippy.cpp

[snippy][NFC] move random seed initialization to Config

[snippy][NFC] move random seed initialization to Config

---

llvm/tools/llvm-snippy/CMakeLists.txt
llvm/tools/llvm-snippy/include/CMakeLists.txt
llvm/tools/llvm-snippy/include/snippy/Support/Options.td
llvm/tools/llvm-snippy/lib/CMakeLists.txt
llvm/tools/llvm-snippy/lib/Options.td
llvm/tools/llvm-snippy/llvm-snippy.cpp
llvm/tools/llvm-snippy/utils/CMakeLists.txt
llvm/tools/llvm-snippy/utils/TableGen/CMakeLists.txt
llvm/tools/llvm-snippy/utils/TableGen/SnippyOptions.cpp
llvm/tools/llvm-snippy/utils/TableGen/SnippyOptions.h
llvm/tools/llvm-snippy/utils/TableGen/TableGen.cpp

[snippy] Generate driver options with tablegen

[snippy] Generate driver options with tablegen

---

llvm/test/tools/llvm-snippy/dump-mir-check-target-triple.yaml
llvm/test/tools/llvm-snippy/dump-options-without-layout.test
llvm/test/tools/llvm-snippy/list-opcode-names-without-layout.test
llvm/test/tools/llvm-snippy/march-with-isa-string.yaml
llvm/test/tools/llvm-snippy/mtriple.yaml
llvm/test/tools/llvm-snippy/unimplemented-march.yaml
llvm/test/tools/llvm-snippy/unknown-target.yaml
llvm/test/tools/llvm-snippy/warning_list.yaml
llvm/test/tools/llvm-snippy/wdisable-option.yaml
llvm/tools/llvm-snippy/include/snippy/Generator/LLVMState.h
llvm/tools/llvm-snippy/include/snippy/Support/DiagnosticInfo.h
llvm/tools/llvm-snippy/lib/Generator/LLVMState.cpp
llvm/tools/llvm-snippy/lib/Options.td
llvm/tools/llvm-snippy/llvm-snippy.cpp

Fixes https://github.com/syntacore/snippy/issues/16

[snippy] Replace march with mtriple

---

llvm/test/tools/llvm-snippy/zvfh-sew8.yaml
llvm/test/tools/llvm-snippy/zvfh.yaml
llvm/test/tools/llvm-snippy/zvfhmin.yaml
llvm/tools/llvm-snippy/include/snippy/Generator/LLVMState.h
llvm/tools/llvm-snippy/include/snippy/Generator/SnippyModule.h
llvm/tools/llvm-snippy/lib/Generator/GeneratorContext.cpp
llvm/tools/llvm-snippy/lib/Generator/SnippyModule.cpp
llvm/tools/llvm-snippy/lib/Target/RISCV/RISCVGenerated.h
llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp

[snippy] support Zvfh and Zvfhmin

[snippy] support Zvfh and Zvfhmin

---

llvm/test/tools/llvm-snippy/rvv-config-histogram/dump-discarded-file.yaml

[snippy] Use unique filenames for output in dump-discarded-file.yaml test

[snippy] Use unique filenames for output in dump-discarded-file.yaml test

---

llvm/tools/llvm-snippy/lib/Generator/GenerationUtils.cpp

[snippy] Fix access alignment for burst mode
Previously the code did the unthinkable:
```
StrongestAR.AccessAlignment =
OpcodeToAR.at(*StrongestAccessSize).AccessAlignment;
```
That is most certainly broken. The correct thing to do is to
get the maximum required alignment, not the alignment of
the largest access size. This would lead to unintentional
generation of misaligned accesses when the same base register
is used for the case like:
- `AccessSize` = `4`, `AccessAlignment` = `4`
- `AccessSize` = `8`, `AccessAlignment` = `1`
In this case the minimum required alignment is `4`, but the
code prior to this change would drop the restriction to `1`.
While we are at it, also clean up this copy-paste pasta with some macros.

[snippy] Fix access alignment for burst mode

---

llvm/tools/llvm-snippy/include/snippy/Config/ImmediateHistogram.h

[snippy][fix] correctly sample shifted signed integers
Previously genImmInInterval was sampling random signed values and
shifting them left by ZeroBits. This caused UB every time negative value
was sampled. To fix this we instead sample positive-values only and then
sign-extend them to interpret as negative if they are.

[snippy][fix] correctly sample shifted signed integers

---

llvm/tools/llvm-snippy/docs/index.rst

[snippy] Description of the default value of the redefine-sp in the documentation

[snippy] Description of the default value of the redefine-sp in the documentation

---

llvm/tools/llvm-snippy/include/snippy/Config/MemoryScheme.h
llvm/tools/llvm-snippy/include/snippy/Generator/Interpreter.h
llvm/tools/llvm-snippy/include/snippy/Simulator/Simulator.h
llvm/tools/llvm-snippy/lib/Generator/FunctionGeneratorPass.cpp
llvm/tools/llvm-snippy/lib/Generator/Interpreter.cpp
llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp

[snippy] During tracking mode, snippy runs code even if it doesn't fit into RX section

[snippy] During tracking mode, snippy runs code even if it doesn't fit into RX section
