llvm/test/tools/llvm-snippy/auto-reserve-regs-for-call.yaml, llvm/tools/llvm-snippy/include/snippy/Target/Target.h, llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp, llvm/tools/llvm-snippy/lib/Target/X86/Target.cpp, llvm/tools/llvm-snippy/llvm-snippy.cpp
tp and gp registers should be valid if we call external functions. We
can reserve these registers for the whole snippet to avoid their
corruption.
=> [snippy] Automatically reserve gp and tp if external callees are present

llvm/test/tools/llvm-snippy/lit.local.cfg
Add a way to filter RVV tests
This commit adds support for "REQUIRES: riscv-rvv" to provide more precise
filtering of tests containing RVV instructions.
=> [snippy] Remove 'model' from riscv-rvv requirement

llvm/test/tools/llvm-snippy/reserved-regs/FP-reserved-aliases-2.yaml, llvm/test/tools/llvm-snippy/reserved-regs/FP-reserved-aliases-3.yaml, llvm/test/tools/llvm-snippy/reserved-regs/FP-reserved-aliases-4.yaml, llvm/test/tools/llvm-snippy/reserved-regs/FP-reserved-aliases.yaml, llvm/test/tools/llvm-snippy/reserved-regs/Inputs/rvv-unit-all.yaml, llvm/test/tools/llvm-snippy/reserved-regs/Inputs/stack-all-reserved-layout.yaml, llvm/test/tools/llvm-snippy/reserved-regs/reserved-reg-2.yaml, llvm/test/tools/llvm-snippy/reserved-regs/reserved-reg-alt-names.yaml, llvm/test/tools/llvm-snippy/reserved-regs/reserved-reg-fail.yaml, llvm/test/tools/llvm-snippy/reserved-regs/reserved-reg-in-yaml.yaml, llvm/test/tools/llvm-snippy/reserved-regs/reserved-reg.yaml, llvm/test/tools/llvm-snippy/reserved-regs/rvv-reserved-aliases-2.yaml, llvm/test/tools/llvm-snippy/reserved-regs/rvv-reserved-aliases.yaml, llvm/test/tools/llvm-snippy/reserved-regs/stack-all-reserved.yaml, llvm/tools/llvm-snippy/include/snippy/Generator/AccessMaskBit.h, llvm/tools/llvm-snippy/include/snippy/Generator/GeneratorContext.h, llvm/tools/llvm-snippy/include/snippy/Generator/Policy.h, llvm/tools/llvm-snippy/include/snippy/Generator/RegisterPool.h, llvm/tools/llvm-snippy/include/snippy/Target/Target.h, llvm/tools/llvm-snippy/lib/Generator/Generation.cpp, llvm/tools/llvm-snippy/lib/Generator/RegisterPool.cpp, llvm/tools/llvm-snippy/lib/LoopLatcherPass.cpp, llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp, llvm/tools/llvm-snippy/llvm-snippy.cpp
To solve the problem with register reservation,
it was necessary to prohibit the reservation of non-physical registers.
=> [snippy] FP register aliases must be taken into account

llvm/tools/llvm-snippy/Model/RISCVModel/RVM.h, llvm/tools/llvm-snippy/Model/RISCVModel/RVM.hpp
This commit adds vector crypto extensions enumerations to model interface.
=> [snippy] Update RISCVModel interface v15->v16.

llvm/tools/llvm-snippy/lib/BlockGenPlanningPass.cpp
[snippy]: Replace deprecated `erase_value` -> `erase`
=> [snippy]: Replace deprecated `erase_value` -> `erase`

llvm/tools/llvm-snippy/include/snippy/Generator/SnippyModule.h, llvm/tools/llvm-snippy/lib/FlowGenerator.cpp, llvm/tools/llvm-snippy/lib/Generator/SnippyModule.cpp, llvm/tools/llvm-snippy/lib/PrologueEpilogueInsertionPass.cpp
[snippy] Account spill of the real stack pointer
Stack pointer role can be given to an arbitrary callee-saved register. In this
case a spill (and fill) of this register is necessary. This spill must be
accounted when we initialize a model for a tracking mode (selfcheck, backtrack,
data hazards).
=> [snippy] Account spill of the real stack pointer

llvm/test/tools/llvm-snippy/branches/sections-bad-alignment.yaml, llvm/tools/llvm-snippy/include/snippy/Config/MemoryScheme.h, llvm/tools/llvm-snippy/llvm-snippy.cpp
[snippy] Improve diagnostics when section start is not a multiply of loop alignment
=> [snippy] Improve diagnostics when section start is not a multiply of loop alignment

llvm/tools/llvm-snippy/include/snippy/Support/Options.h, llvm/tools/llvm-snippy/lib/Support/Options.cpp
[snippy][perf]: Remove linear lookups for snippy options
As it turns out snippy spends a lot of time (~30%) in hot loops
looking up options values. This is a huge performance regression introduced in
by option aliases. Implementing this as a `std::unordered_map<StringRef, std::shared_ptr<_>>`
alleviates the problem.
Additionally this patch gets rid of unnecessary allocations in `std::string`
by using `StringRef` to store option names. They are already required to be static lifetime
since `snippy::opt` (and cosequently `cl::opt`) takes names by `const char *`.
This trivially improves snippy runtime by up to 60% (18s -> 7s) on some tests.
=> [snippy][perf]: Remove linear lookups for snippy options

llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation-disabled.yaml, llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation-error-bit-values-negative-value-ranges.yaml, llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation-error-bit-values-negative-value.yaml, llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation-error-integral-range-rounding-mode.yaml, llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation-error-ranges-too-large.yaml, llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation-error-too-large.yaml, llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation-error-values-too-large.yaml, llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation-error.yaml, llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation-extended-overwrite-value-configuration.yaml, llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation-integral-range-all-rounding-modes.yaml, llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation-stress.yaml, llvm/test/tools/llvm-snippy/floating-point/float-nan-propagation.yaml, llvm/tools/llvm-snippy/include/snippy/Config/FPUSettings.h, llvm/tools/llvm-snippy/include/snippy/Config/RegisterHistogram.h, llvm/tools/llvm-snippy/include/snippy/Config/SerDesUtils.h, llvm/tools/llvm-snippy/include/snippy/Config/Valuegram.h, llvm/tools/llvm-snippy/include/snippy/Generator/GeneratorContext.h, llvm/tools/llvm-snippy/include/snippy/Support/APIntSampler.h, llvm/tools/llvm-snippy/include/snippy/Support/Error.h, llvm/tools/llvm-snippy/include/snippy/Support/RandUtil.h, llvm/tools/llvm-snippy/include/snippy/Support/YAMLUtils.h, llvm/tools/llvm-snippy/lib/Config/FPUSettings.cpp, llvm/tools/llvm-snippy/lib/Config/RegisterHistogram.cpp, llvm/tools/llvm-snippy/lib/Config/Valuegram.cpp, llvm/tools/llvm-snippy/lib/Generator/Generation.cpp, llvm/tools/llvm-snippy/lib/Generator/GeneratorContext.cpp, llvm/tools/llvm-snippy/lib/Support/APIntSampler.cpp, llvm/tools/llvm-snippy/lib/Support/CMakeLists.txt, llvm/tools/llvm-snippy/llvm-snippy.cpp
[snippy]: Detailed float overwrite value configuration 
This patch implements fine-grained control over floating-point
overwrite value selection. A minimal example of configuration:
```yaml
fpu-config:
overwrite:
ieee-double:
valuegram:
- [0x0fffffffffffff, 1.0]
- [uniform, 1.0]
- [bitpattern, 1.0]
- type: bitpattern
weight: 1.0 # by default
- type: bitrange
min: 0x8000000000000001
max: 0x800fffffffffffff
weight: 1.0
range: # - treated as integers
min: 1
max: 3
```
- The behaviour of `range` configuration is preserved. min/max values
are treated as integer values and are semantically converted to the
appropriate (according to the semantics) floating-point value in RNE rounding mode.
By default overwrite fills the registers with uniformly distributed bits,
as opposed to the previous …
=> [snippy]: Detailed float overwrite value configuration  (revived)

llvm/tools/llvm-snippy/include/snippy/Support/DiagnosticInfo.h, llvm/tools/llvm-snippy/lib/Support/DiagnosticInfo.cpp
[snippy][NFC]: Mark snippy::fatal with [[noreturn]]
For DiagnosticSeverity of llvm::DS_Error SnippyDiagnosticInfo
always uses report_fatal_error:
```
if (Severity == llvm::DS_Error)
llvm::report_fatal_error(StringRef(Description), false);
```
So snippy::fatal will never return, since llvm::report_fatal_error
is also [[noreturn]].
=> [snippy][NFC]: Mark snippy::fatal with [[noreturn]]

llvm/test/tools/llvm-snippy/memory-scheme/ranges-diag.yaml, llvm/test/tools/llvm-snippy/memory-scheme/scheme-generation-option.yaml, llvm/tools/llvm-snippy/include/snippy/Support/DiagnosticInfo.h, llvm/tools/llvm-snippy/lib/Config/MemoryScheme.cpp, llvm/tools/llvm-snippy/lib/MemAccessDumperPass.cpp, llvm/tools/llvm-snippy/lib/Support/DiagnosticInfo.cpp, llvm/tools/llvm-snippy/llvm-snippy.cpp
[snippy]: Color diagnostic output when possible
This patch rips out most of the incorrect diagnostics that write
to errs() directly and replaces them with proper `snippy::warn()` calls.
Now snippy::{fatal,warn,notice,remark} color their output for visibility.
We already had this behavior for YAML diagnostics, since those use SMDiagnostic,
which uses the same `WithColor` mechanism for coloring the output diagnostic severity.
=> [snippy]: Color diagnostic output when possible

llvm/tools/llvm-snippy/include/snippy/Generator/RandomMemAccSampler.h, llvm/tools/llvm-snippy/include/snippy/Support/MemAccessGenerator.h, llvm/tools/llvm-snippy/lib/Generator/RandomMemAccSampler.cpp
Currently we use OwningMAG in which we copy all memory accesses. And we do this
for every instr-class (attributes combination). This leads not only to
excessive copies (that slow snippy down) but also to incorrectly working
ordered access-addresses schemes Now they are ordered inside each instr-class
and not across classes.
=> [snippy] non-owning MAG

llvm/tools/llvm-snippy/include/snippy/Generator/Interpreter.h, llvm/tools/llvm-snippy/include/snippy/Generator/SimRunner.h, llvm/tools/llvm-snippy/lib/Generator/Interpreter.cpp, llvm/tools/llvm-snippy/lib/Generator/SimRunner.cpp, llvm/tools/llvm-snippy/lib/Generator/SimulatorContextWrapperPass.cpp
[snippy] Disable .bss initialization during loading elf to model
This is done to comply with legacy behavior of previous versions that didn't
do that.
=> [snippy] Disable .bss initialization during loading elf to model

llvm/tools/llvm-snippy/include/snippy/Generator/GlobalsPool.h, llvm/tools/llvm-snippy/include/snippy/Generator/Policy.h, llvm/tools/llvm-snippy/include/snippy/Support/DiagnosticInfo.h, llvm/tools/llvm-snippy/include/snippy/Support/Error.h, llvm/tools/llvm-snippy/include/snippy/Support/RandUtil.h, llvm/tools/llvm-snippy/lib/Config/FPUSettings.cpp, llvm/tools/llvm-snippy/lib/Config/OpcodeHistogram.cpp, llvm/tools/llvm-snippy/lib/Config/RegisterHistogram.cpp, llvm/tools/llvm-snippy/lib/Config/Valuegram.cpp, llvm/tools/llvm-snippy/lib/Generator/Generation.cpp, llvm/tools/llvm-snippy/lib/Generator/GenerationUtils.cpp, llvm/tools/llvm-snippy/lib/Generator/LLVMState.cpp, llvm/tools/llvm-snippy/lib/Generator/Policy.cpp, llvm/tools/llvm-snippy/lib/Generator/RandomMemAccSampler.cpp, llvm/tools/llvm-snippy/lib/Generator/SnippyModule.cpp, llvm/tools/llvm-snippy/lib/Generator/TopMemAccSampler.cpp, llvm/tools/llvm-snippy/lib/Support/CMakeLists.txt, llvm/tools/llvm-snippy/lib/Support/Error.cpp
\[snippy\] Refactor error handling (NFC)
Get rid of the illegal pattern:
```{.cpp}
if (auto Err = Expected.takeError()) {
....
}
someUsage(*Expected);
```
This is not allowed because of the implicit postcondition for Expected::takeError():
> Take ownership of the stored error. After calling this the Expected is in an indeterminate state that can only be safely destructed. No further calls (beside the destructor) should be made on the Expected value.
=> [snippy] Refactor error handling (NFC)

llvm/test/tools/llvm-snippy/init-regs-in-elf-liveness.yaml, llvm/tools/llvm-snippy/include/snippy/Target/Target.h, llvm/tools/llvm-snippy/lib/Generator/FunctionGeneratorPass.cpp, llvm/tools/llvm-snippy/lib/RegsInitInsertionPass.cpp, llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp, llvm/tools/llvm-snippy/lib/Target/X86/Target.cpp
[snippy] add a method for adding livein registers for basic block
=> [snippy] add liveness when using init-regs-in-elf

.github/workflows/workflow.yml
Since most of the changes to don't cause core LLVM rebuilds CI
can be drastically sped up by just caching ccache artifacts.
Other notable things done:
- Use sparse git checkout only necessary for `llvm-snippy` tool.
- Pin runner image to `ubuntu-24.04`.
- Add missing `cmake` to install. Useful to run the job locally.
=> [snippy][ci] Refactor and use actions/cache with ccache for faster CI

.github/workflows/workflow.yml
This enables caching of `NATIVE` tools like `llvm-tblgen` to further speed up CI.
> [!NOTE]  
> This bring down the CI job runtime to around 3 minutes when everything is cached.
=> [snippy][ci] Enable `LLVM_EXTERNAL_PROJECT_PASSTHROUGH` for ccache

llvm/test/tools/llvm-snippy/invalid-cpu-fail.test, llvm/test/tools/llvm-snippy/void-param-list.yaml, llvm/tools/llvm-snippy/include/snippy/Generator/LLVMState.h, llvm/tools/llvm-snippy/lib/Generator/LLVMState.cpp, llvm/tools/llvm-snippy/llvm-snippy.cpp
[snippy] Diagnose unrecognized cpu for subtarget
Refactor LLVMState to make constructor failable and add
missing special member functions.
Add diagnostics for unrecognized cpu name for earlier
and more concise error messages.
=> [snippy] Diagnose unrecognized cpu for subtarget

llvm/test/tools/llvm-snippy/dump-options-without-layout.test, llvm/test/tools/llvm-snippy/lit.local.cfg, llvm/test/tools/llvm-snippy/non-reproducible-exec-error.yaml, llvm/test/tools/llvm-snippy/wdisable-option.yaml, llvm/test/tools/llvm-snippy/wdisable-unknown.yaml, llvm/test/tools/llvm-snippy/werror.yaml, llvm/test/tools/llvm-snippy/wno-error.yaml, llvm/tools/llvm-snippy/include/snippy/Support/DiagnosticInfo.h, llvm/tools/llvm-snippy/lib/Config/Config.cpp, llvm/tools/llvm-snippy/lib/Support/DiagnosticInfo.cpp
[snippy] Configurable Werror and Wno-error options
This commit implements some new functionality to handle warning and
error reporting. New -Werror option can now accept a list of warning
categories that should be treated like errors (empty means all). New
-Wno-error option allows to disable reporting errors on selected warning
categories even if -Werror is enabled for them. This commit also adds
new diagnostic (non-reproducible-execution) that prevents using model
execution without register initialization as it will lead to non
reproducible execution
=> [snippy] Configurable Werror and Wno-error options

llvm/lib/Target/RISCV/RISCVInstrInfoZfa.td
This is represented in the MachineInstr and MCInst as a 5-bit unsigned immediate so we use OPERAND_UIMM5. If someone needs to know for sure its an FLI constant in the future we can break it out to a new type.
(This is a cherry-pick of c62130f7b35412e7caadf5fd9547f21a736c4543)
=> [RISCV] Add OperandType to loadfpimm. (#114150)

llvm/tools/llvm-snippy/lib/Generator/Interpreter.cpp, llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp
Use APInts of xlen size when calculating offsets and addresses for rv32
In some cases we have assertions from APInt:
Assertion `llvm::isUIntN(BitWidth, val) && "Value is not an N-bit unsigned value"'
This happens, because we use uint64_t for calculations and is some cases rely on
wrapping around zero. Instead of uint64_t we should use xlen-based type.
=> [snippy] Use APInts of xlen size when calculating offsets and addresses for rv32

llvm/tools/llvm-snippy/include/snippy/Config/Branchegram.h, llvm/tools/llvm-snippy/include/snippy/Generator/LoopLatcherPass.h, llvm/tools/llvm-snippy/include/snippy/Support/DiagnosticInfo.h, llvm/tools/llvm-snippy/include/snippy/Target/Target.h, llvm/tools/llvm-snippy/lib/Config/Branchegram.cpp, llvm/tools/llvm-snippy/lib/LoopLatcherPass.cpp, llvm/tools/llvm-snippy/lib/Target/RISCV/RISCVGenerated.h, llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp, llvm/tools/llvm-snippy/lib/Target/X86/Target.cpp
This patch introduces loop counter stride randomization.
Example in .yaml config:
```yaml
branches:
loop-counters:
random-stride:
enabled: <on/off> # optional
min: 5 # optional
max: 10 # optional
```
Something from [enabled, min, max] list must be specified, otherwise an error
occurs
=> [snippy] Improve randomness of loop counter stride

llvm/test/tools/llvm-snippy/branches/rvc-and-reserved.yaml, llvm/test/tools/llvm-snippy/cl-options-error-toplevel.yaml, llvm/tools/llvm-snippy/lib/Config/Config.cpp
[snippy][Config] Diagnose unknown YAML keys
This patch ensures that unknown keys in snippy configuration
are not warnings but hard errors. This was previously tricky
to do because Config is parsed several times:
- Once to only read options like mtriple e.t.c.
- The second time to actually fill the Config. This time
options are completely ignored.
=> [snippy][Config] Diagnose unknown YAML keys

llvm/test/tools/llvm-snippy/rv32-almost-large-section-address.yaml, llvm/test/tools/llvm-snippy/rv32-large-acces-ranges-end.yaml, llvm/test/tools/llvm-snippy/rv32-large-acces-ranges-start.yaml, llvm/test/tools/llvm-snippy/rv32-large-access-address-access-size.yaml, llvm/test/tools/llvm-snippy/rv32-large-access-address-addr.yaml, llvm/test/tools/llvm-snippy/rv32-large-access-evictions-fixed.yaml, llvm/test/tools/llvm-snippy/rv32-large-access-evictions-mask.yaml, llvm/test/tools/llvm-snippy/rv32-large-section-address.yaml, llvm/tools/llvm-snippy/include/snippy/Config/MemoryScheme.h, llvm/tools/llvm-snippy/lib/Config/MemoryScheme.cpp
This commit adds a check to validate addresses in the configuration file, ensuring they do not exceed the address space size.
=> [snippy] Check that config addresses fit in address space size

llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp
[snippy][RISCV] Get rid of unnecessary copying of MCRegisterInfo
This would result in snippy spending about %40 of the total runtime
in the std::vector<unsigned> copy constructor.
=> [snippy][RISCV] Get rid of unnecessary copying of MCRegisterInfo

llvm/lib/Target/RISCV/RISCVInstrInfo.td, llvm/test/tools/llvm-snippy/floating-point/float-read-write-fcsr-imm-hist.yaml, llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp
This patch adds several pseudoinstructions for working with FCSR:
- `ReadFCSR`
- `WriteFCSRImm`
- `SwapFCSRImm`
=> [snippy] Add ReadFCSR, WriteFCSRImm, SwapFCSRImm pseudoinstructions

llvm/tools/llvm-snippy/lib/Generator/Generation.cpp
[snippy] Avoid copying MCRegisterInfo (take 2)
Copying MCRegisterInfo is really expensive and snippy spends about ~15%
runtime in just this copy constructor.
=> [snippy] Avoid copying MCRegisterInfo (take 2)

llvm/tools/llvm-snippy/include/snippy/Generator/RegisterPool.h, llvm/tools/llvm-snippy/include/snippy/Target/Target.h, llvm/tools/llvm-snippy/lib/Config/Config.cpp, llvm/tools/llvm-snippy/lib/Generator/Generation.cpp, llvm/tools/llvm-snippy/lib/Generator/GenerationUtils.cpp, llvm/tools/llvm-snippy/lib/Generator/OperandsReinitializationPolicy.cpp, llvm/tools/llvm-snippy/lib/Generator/RegisterGenerator.cpp, llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp, llvm/tools/llvm-snippy/lib/Target/X86/Target.cpp
[snippy] Get rid of unnecessary allocations
Splitting units to physical registers is very frequently
used in register generation/selection and the overhead of
allocating a new `std::vector` for each call there is too much.
Just switching to `SmallVector` in the signature speeds up
the generation by ~30%.
=> [snippy] Get rid of unnecessary allocations

llvm/tools/llvm-snippy/include/snippy/Generator/LLVMState.h, llvm/tools/llvm-snippy/include/snippy/Generator/Policy.h, llvm/tools/llvm-snippy/lib/BlockGenPlanningPass.cpp, llvm/tools/llvm-snippy/lib/Generator/GenerationUtils.cpp, llvm/tools/llvm-snippy/lib/PostGenVerifierPass.cpp
[snippy] Avoid calling getSubtargetImpl for `Function`
`LLVMTargetMachine::getSubtargetImpl` is quite expensive to call and
currently snippy spends around 10% in just getSubtargetImpl. This can
easily be avoided by just looking up the TargetSubtargetInfo from the
MachineFunction.
=> [snippy] Avoid calling getSubtargetImpl for `Function`

llvm/test/tools/llvm-snippy/branches/consecutive-loops-unconditional-branch-all.yaml, llvm/test/tools/llvm-snippy/branches/consecutive-loops-unconditional-branch.yaml, llvm/test/tools/llvm-snippy/branches/disabled-consecutive-loops-unconditional-branch.yaml, llvm/tools/llvm-snippy/include/snippy/Config/Config.h, llvm/tools/llvm-snippy/include/snippy/Config/OpcodeHistogram.h, llvm/tools/llvm-snippy/lib/Generator/CFPermutation.cpp
[snippy] Histogram diagnostic for unconditional branches when the ‘consecutive-loops’ is enabled
This commit adds a check for unconditional branches in histogram if 'consecutive-loops' is enabled. We need this diagnostic because unconditional branches with consecutive loops leeds to infinite loop.
=> [snippy] Consecutive loops diagnostic

llvm/tools/llvm-snippy/lib/Target/RISCV/CMakeLists.txt, llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp, llvm/tools/llvm-snippy/utils/TableGen/CMakeLists.txt, llvm/tools/llvm-snippy/utils/TableGen/Emitters.h, llvm/tools/llvm-snippy/utils/TableGen/RISCVGenerated.cpp, llvm/tools/llvm-snippy/utils/TableGen/TableGen.cpp
[snippy] Exclude AsmParserOnly and CodeGenOnly instructions from OpcodeCache
This change excludes AsmParserOnly from the list of supported opcodes.
Prior to this `-list-opcode-names` listed assembler-only insn directives
as valid opcodes:
```
12822 Insn32
12823 InsnB
12833 InsnI
12834 InsnI_Mem
12835 InsnJ
12836 InsnR
12837 InsnR4
12838 InsnS
12839 InsnU
```
=> [snippy] Exclude AsmParserOnly and CodeGenOnly instructions from OpcodeCache

llvm/tools/llvm-snippy/Model/RISCVModel/RVM.h, llvm/tools/llvm-snippy/Model/RISCVModel/RVM.hpp, llvm/tools/llvm-snippy/Model/RISCVModel/VTable.h, llvm/tools/llvm-snippy/include/snippy/Generator/Interpreter.h, llvm/tools/llvm-snippy/include/snippy/Simulator/Observer.h, llvm/tools/llvm-snippy/include/snippy/Simulator/Simulator.h, llvm/tools/llvm-snippy/include/snippy/Simulator/Targets/RISCV.h, llvm/tools/llvm-snippy/include/snippy/Simulator/Transactions.h, llvm/tools/llvm-snippy/include/snippy/Target/Target.h, llvm/tools/llvm-snippy/lib/Generator/Generation.cpp, llvm/tools/llvm-snippy/lib/Generator/Interpreter.cpp, llvm/tools/llvm-snippy/lib/Simulator/Common.h, llvm/tools/llvm-snippy/lib/Simulator/RISCVSimulator.cpp, llvm/tools/llvm-snippy/lib/Simulator/Transactions.cpp, llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp, llvm/tools/llvm-snippy/lib/Target/X86/Target.cpp
\[snippy\] Allow modifying CSRs inside loops with selfcheck
This commit makes it possible to generate CSR reads and writes inside loops with selfcheck/hazard modes with introduction of CSR update callbacks.
=> [snippy] Allow modifying CSRs inside loops with selfcheck

llvm/tools/llvm-snippy/include/snippy/Simulator/Targets/RISCV.h, llvm/tools/llvm-snippy/lib/Simulator/RISCVSimulator.cpp, llvm/tools/llvm-snippy/lib/Target/RISCV/Target.cpp
[snippy][fix] use correct units for reg width
Before this commit RISCVRegisterState::getMaxRegValueForSize was
expecting XLen value in bytes but was getting it in bits, which caused
assigning 64 to RegSizeInBytes enum variable (which is out of range for
this non-class enum type).
=> [snippy][fix] use correct units for reg width

llvm/test/tools/llvm-snippy/linker-sections-prefix.yaml, llvm/tools/llvm-snippy/docs/index.rst, llvm/tools/llvm-snippy/lib/Generator/Linker.cpp
[snippy] Section names prefix override option
This commit adds a new snippy option "sections-prefix" that changes section names prefix ("snippy" by default).
=> [snippy] Section names prefix override option

llvm/tools/llvm-snippy/include/snippy/Config/Config.h, llvm/tools/llvm-snippy/lib/Config/Config.cpp, llvm/tools/llvm-snippy/lib/Config/Options.td, llvm/tools/llvm-snippy/lib/PrologueEpilogueInsertionPass.cpp
[snippy] Add 'skip-legacy-sp-spill' to skip spilling SP without honor-target-abi
Adds a new option that should become the default in new releases. Fix some typos
while we are at it.
=> [snippy] Add 'skip-legacy-sp-spill' to skip spilling SP without honor-target-abi
